### ISSUE TITLE
Bridge creates new room for each new message in private chat with VK user

### ISSUE THREAD

**Issue by MurzNN** [innereq/mx-puppet-vk#5]
Bridge works well for most of chats, but for one user it can't create a room on Matix side for private chat.

On each new incoming message from that user - I receive invite to new room, I join to it successfully (see me and right puppeted user in members), but didn't see the sent message in timeline (timeline is empty).

And on each new message from that user - bridge creates new room and send invite, but the room timeline is empty.

**Comment by MurzNN** [comment]
Here is log record when receiving new event from this user on VK side:
```
 Jan-25 12:37:08.874 [bot-sdk-Appservice] info: Processing transaction 2072
 Jan-25 12:37:08.875 [bot-sdk-Appservice] info: Processing event of type m.room.member
 Jan-25 12:37:08.876 [MatrixEventHandler] info: Got new user join event from @murz:ru-matrix.org in !UAQonavgLiDOsmjuGN:ru-matrix.org...
 127.0.0.1 - - [25/Jan/2021:09:37:08 +0000] "PUT /transactions/2072?access_token=[censored] HTTP/1.1" 200 2 "-" "Synapse/1.25.0"
 Jan-25 12:37:08.889 [bot-sdk-MatrixLiteClient] info: (REQ-3) GET http://localhost:8008/_matrix/client/r0/rooms/!UAQxxxvgLiDOsmjuGN%3Aru-matrix.org/state/m.room.power_levels/
 Jan-25 12:37:18.331 [MatrixEventHandler] error: Error checking mute status Error: Failed to resolve room !UAQxxxvgLiDOsmjuGN:ru-matrix.org
     at Provisioner.<anonymous> (mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/provisioner.js:397:23)
     at Generator.next (<anonymous>)
     at fulfilled (mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/provisioner.js:17:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by MurzNN** [comment]
Also in logs I see timeout errors, maybe they are the source of this issue?
Here is full log record:
```
 Jan-25 13:18:18.079 [bot-sdk-MatrixLiteClient] error: (REQ-2) RequestError: Timeout awaiting 'request' for 60000ms
     at ClientRequest.<anonymous> (/opt/matrix/bridges/mx-puppet-vk/node_modules/got/dist/source/core/index.js:953:65)
     at Object.onceWrapper (events.js:422:26)
     at ClientRequest.emit (events.js:327:22)
     at ClientRequest.origin.emit (/opt/matrix/bridges/mx-puppet-vk/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
     at Socket.socketErrorListener (_http_client.js:432:9)
     at Socket.emit (events.js:315:20)
     at emitErrorNT (internal/streams/destroy.js:84:8)
     at processTicksAndRejections (internal/process/task_queues.js:84:21)
     at Timeout.timeoutHandler [as _onTimeout] (/opt/matrix/bridges/mx-puppet-vk/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
     at listOnTimeout (internal/timers.js:551:17)
     at processTimers (internal/timers.js:492:7) {
   name: 'TimeoutError',
   code: 'ETIMEDOUT',
   timings: {
     start: 1611569838074,
     socket: 1611569838075,
     lookup: 1611569838075,
     connect: 1611569838075,
     secureConnect: undefined,
     upload: 1611569838075,
     response: undefined,
     end: undefined,
     error: 1611569898076,
     abort: undefined,
     phases: {
       wait: 1,
       dns: 0,
       tcp: 0,
       tls: undefined,
       request: 0,
       firstByte: undefined,
       download: undefined,
       total: 60002
     }
   },
   event: 'request'
 }
 Jan-25 13:18:18.081 [RoomSync] error: Error fetching mxid: TypeError: Cannot read property 'errcode' of undefined
     at RoomSyncroniser.<anonymous> (/opt/matrix/bridges/mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/roomsyncroniser.js:211:38)
     at Generator.throw (<anonymous>)
     at rejected (/opt/matrix/bridges/mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/roomsyncroniser.js:18:65)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 Jan-25 13:18:18.082 [VKPuppet:vk] error: Error handling vk message event TypeError: Cannot read property 'errcode' of undefined
     at RoomSyncroniser.<anonymous> (/opt/matrix/bridges/mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/roomsyncroniser.js:211:38)
     at Generator.throw (<anonymous>)
     at rejected (/opt/matrix/bridges/mx-puppet-vk/node_modules/mx-puppet-bridge/lib/src/roomsyncroniser.js:18:65)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by MurzNN** [comment]
Yes, all becomes well when I speed-up Synapse, so this issue we can fix when https://github.com/Sorunome/mx-puppet-bridge/issues/74 will be implemented, so let's close this.
