### ISSUE TITLE
Chats with communities (groups) have bad (numeric) titles in Matrix room

### ISSUE THREAD

**Issue by MurzNN** [innereq/mx-puppet-vk#7]
When I start chat with community (VK Group), the room on Matrix side got the numeric title (eg -183375547 for https://vk.com/itlandiann), instead of group name. Will be good to fix this.

**Comment by inexcode** [comment]
Probably https://github.com/innereq/mx-puppet-vk/blob/master/src/vk.ts#L93 was created by me to handle this case, but I didn't write a case for groups. Thanks.

**Comment by inexcode** [comment]
Should be fixed now, but I cannot test.

**Comment by MurzNN** [comment]
I tried with last release, but got the error:
```
 Feb-15 23:13:29.787 [VKPuppet:vk] info: Recieved something!
 Feb-15 23:13:29.788 [VKPuppet:vk] debug: Received new message! MessageContext {
   id: 98742,
   conversationMessageId: 2,
   peerId: -202620575,
   peerType: 'group',
   senderId: -202620575,
   senderType: 'group',
   createdAt: 1613420009,
   updatedAt: 0,
   text: 'Здрасьте',
   forwards: MessageForwardsCollection(0) [],
   attachments: [],
   isOutbox: false,
   type: 'message',
   subTypes: [
     'message_new'
   ],
   state: {}
 }
 Feb-15 23:13:30.038 [VKPuppet:vk] error: Error handling vk message event APIError: Code №100 - One of the parameters specified was missing or invalid: group_ids is undefined
     at SequentialWorker.execute (mx-puppet-vk/node_modules/vk-io/lib/index.js:1524:39)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   code: 100,
   params: [
     { key: 'method', value: 'groups.getById' },
     { key: 'oauth', value: '1' },
     { key: 'v', value: '5.124' },
     { key: 'group_id', value: '-202620575' }
   ]
 }
```
